### ISSUE TITLE
osm ne s'affiche pas

### ISSUE THREAD

**Issue by nalafal** [StrasWeb/events-manager-osm#1]
Bonjour

Je suis en WP 4.3.2 avec event manager dernière version, et ce plugin ne semble pas fonctionner. Par défaut, la carte affiché reste celle de GM. Y a t'il une étape que j'ai loupée ?

Merci d'avance, 
nalafal

**Comment by Rudloff** [comment]
Je viens de tester avec WordPress 4.4.1 et Events Manager 5.6.2 et le plugin fonctionne.
Est-ce que ton site est accessible publiquement que je puisse jeter un oeil à la carte qui est générée ?

**Comment by nalafal** [comment]
voici pierre

https://1n19rhrx6tk4rdsswfl1.oasis.sandstorm.io/

Mais ça marche pas très bien pour l'instant en général.

Nicolas

Le 28 janvier 2016 à 11:29, Pierre Rudloff notifications@github.com a
écrit :

**Comment by Rudloff** [comment]
Perso, je vois bien un fond de carte OSM ici : https://1n19rhrx6tk4rdsswfl1.oasis.sandstorm.io/events/non-a-letat-durgence/index.html

**Comment by nalafal** [comment]
Ah d'accord, dans l'éditeur on voit GM, mais c'est OSM qui apparait au
public. Merci de ton aide pierre.

2016-01-28 12:35 GMT+01:00 Pierre Rudloff notifications@github.com:
